package com.eduza.member.jpa.pojo;
// Generated Jan 3, 2018 7:52:18 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import com.eduza.member.jpa.api.UserProfileEntity;

/**
 * UserProfile generated by hbm2java
 */
@Entity
@Table(name = "user_profile",// gen จาก netbeans จะได้เป็น user_profile
        catalog = "jeasy_acamas"
)
public class UserProfile implements java.io.Serializable, UserProfileEntity {

    private Long id;
    //@NotNull
    //@Size(min = 5, max = 20, message = "Username must be between 5 - 20 charaters long.")
    //@Pattern(regexp = "^[a-zA-Z0-0]+$", message = "Username must be alphanumberic with no spaces")
    private String username;

    private String password;
    private String secretCode;
    private String firstName;
    private String midName;
    private String lastName;
    private String displayName;
    private String gender;
    private String email;
    private Date birthDate;
    private Date registedDath;
    private boolean isEnabled;
    private boolean isValidated;
    private Date lastAccessDatetime;
    private String languageCode;
    private String countryCode;

    public UserProfile() {
    }

    public UserProfile(String username, String password, String secretCode, String firstName, String lastName, String email, Date birthDate, boolean isEnabled, boolean isValidated) {
        this.username = username;
        this.password = password;
        this.secretCode = secretCode;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.birthDate = birthDate;
        this.isEnabled = isEnabled;
        this.isValidated = isValidated;
    }

    public UserProfile(String username, String password, String secretCode, String firstName, String midName, String lastName, String displayName, String gender, String email, Date birthDate, Date registedDath, boolean isEnabled, boolean isValidated, Date lastAccessDatetime, String languageCode, String countryCode) {
        this.username = username;
        this.password = password;
        this.secretCode = secretCode;
        this.firstName = firstName;
        this.midName = midName;
        this.lastName = lastName;
        this.displayName = displayName;
        this.gender = gender;
        this.email = email;
        this.birthDate = birthDate;
        this.registedDath = registedDath;
        this.isEnabled = isEnabled;
        this.isValidated = isValidated;
        this.lastAccessDatetime = lastAccessDatetime;
        this.languageCode = languageCode;
        this.countryCode = countryCode;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "username", nullable = false, length = 128)
    @Override
    public String getUsername() {
        return this.username;
    }

    @Override
    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "password", nullable = false, length = 80)
    @Override
    public String getPassword() {
        return this.password;
    }

    @Override
    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "secretCode", nullable = false, length = 32)
    @Override
    public String getSecretCode() {
        return this.secretCode;
    }

    @Override
    public void setSecretCode(String secretCode) {
        this.secretCode = secretCode;
    }

    @Column(name = "firstName", nullable = false, length = 80)
    @Override
    public String getFirstName() {
        return this.firstName;
    }

    @Override
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name = "midName", length = 80)
    @Override
    public String getMidName() {
        return this.midName;
    }

    @Override
    public void setMidName(String midName) {
        this.midName = midName;
    }

    @Column(name = "lastName", nullable = false, length = 80)
    @Override
    public String getLastName() {
        return this.lastName;
    }

    @Override
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Column(name = "displayName", length = 40)
    @Override
    public String getDisplayName() {
        return this.displayName;
    }

    @Override
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    @Column(name = "gender", length = 2)
    @Override
    public String getGender() {
        return this.gender;
    }

    @Override
    public void setGender(String gender) {
        this.gender = gender;
    }

    @Column(name = "email", nullable = false, length = 128)
    @Override
    public String getEmail() {
        return this.email;
    }

    @Override
    public void setEmail(String email) {
        this.email = email;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "birthDate", nullable = false, length = 10)
    @Override
    public Date getBirthDate() {
        return this.birthDate;
    }

    @Override
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

//    /**
//     * *
//     * ของเดิมมันรับเป็น date เปลี่ยนเป็น รับ string เพื่อให้มันใช้กับ form reg
//     * ได้
//     *
//     * @param birthDate
//     */
//    public void setBirthDate(String birthDate) {
//        try {
//            this.birthDate = new SimpleDateFormat("MM/dd/yyyy HH:mm").parse(birthDate);
//        } catch (ParseException ex) {
//            Logger.getLogger(UserProfile.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
//    public void setBirthDateString(String birthDate) {
//     
//    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "registedDath", length = 19)
    @Override
    public Date getRegistedDath() {
        return this.registedDath;
    }

    @Override
    public void setRegistedDath(Date registedDath) {
        this.registedDath = registedDath;
    }

    @Column(name = "isEnabled", nullable = false)
    @Override
    public boolean isIsEnabled() {
        return this.isEnabled;
    }

    @Override
    public void setIsEnabled(boolean isEnabled) {
        this.isEnabled = isEnabled;
    }

    @Column(name = "isValidated", nullable = false)
    @Override
    public boolean isIsValidated() {
        return this.isValidated;
    }

    @Override
    public void setIsValidated(boolean isValidated) {
        this.isValidated = isValidated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "lastAccessDatetime", length = 19)
    @Override
    public Date getLastAccessDatetime() {
        return this.lastAccessDatetime;
    }

    @Override
    public void setLastAccessDatetime(Date lastAccessDatetime) {
        this.lastAccessDatetime = lastAccessDatetime;
    }

    @Column(name = "languageCode", length = 8)
    @Override
    public String getLanguageCode() {
        return this.languageCode;
    }

    @Override
    public void setLanguageCode(String languageCode) {
        this.languageCode = languageCode;
    }

    @Column(name = "countryCode", length = 8)
    @Override
    public String getCountryCode() {
        return this.countryCode;
    }

    @Override
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

}
