package com.eduza.member.jpa.impl;
// Generated Jan 3, 2018 7:52:18 PM by Hibernate Tools 4.3.1

import com.eduza.member.jpa.api.UserProfileRepository;
import java.util.List;
import org.springframework.stereotype.Repository;
import com.eduza.member.jpa.api.UserProfileEntity;
import com.eduza.member.jpa.pojo.UserProfile;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * UserProfile generated by hbm2java
 */
@Repository("userProfileRepository")
public class UserProfileRepositoryImpl implements java.io.Serializable, UserProfileRepository {

    @Autowired
    private SessionFactory sessionFactory;

    /**
     * *
     * เสร็จ
     *
     * @param id
     * @return
     */
    @Override
    public UserProfileEntity findById(Long id) {
        return (UserProfile) sessionFactory.getCurrentSession().get(UserProfile.class, id);
    }

    /**
     * *
     * เสร็จ
     *
     * @param userProfile
     * @return 
     */
    @Override
    public Long saveUserProfile(UserProfileEntity userProfile) {
        Session session = sessionFactory.getCurrentSession();
        //Employee emp = getTestEmployee();
        long id = (Long) session.save(userProfile);
        session.flush(); //address will not get saved without this
        return id;
    }

    @Override
    public void deleteUserProfileById(Long id) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public List<UserProfileEntity> findAllUserProfiles() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
